services:
    database:
        image: postgres
        container_name: movie-theater-db
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - movie-theater-data:/data/postgres
        networks:
            - movie-theater
    backend:
        build: .
        container_name: movie-theater-backend
        ports:
            - 3333:3333
            - 5555:5555
        depends_on:
            - database
        volumes:
          - .:/app
          - /app/node_modules
        environment:
            - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
        networks:
            - movie-theater
volumes:
    movie-theater-data:

networks:
    movie-theater:
