name: Validate Branch Name

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          echo "Branch name: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|refactor|style|docs)\/[a-z0-9-]+$ ]]; then
            echo "Branch name is invalid"
            echo "It must follow the pattern: feat|fix|refactor|style|docs/<lowercase-description-with-dashes>"
            exit 1
          fi

          echo "Branch name is valid!"